import 'package:animate_do/animate_do.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:rollease/models/DotsDecorator.dart';
import 'package:rollease/models/OnBoarding.dart';

part 'sliding_switch.dart';
part 'sidebar.dart';
part 'payment_card.dart';
part 'ovo_balance_card.dart';
part 'add_new_debit_card.dart';
part 'debit_card.dart';
part 'debit_payment_menu.dart';
part 'login_button.dart';
part 'type_of_rent.dart';
part 'onboarding_card.dart';
part 'dots_indicator.dart';
part 'date_field.dart';
part 'primary_container.dart';
